# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI on main branch

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
        java: [ '17']

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
        cache: maven
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      shell: bash

    # - name: Install maven-repository-aws-s3 dependencies
    #   run: |
    #     HOME=$(dirname $(readlink -f $(which mvn)))
    #     echo "HOME: $HOME"
        
    #     for dep in "com.github.ehsaniara:maven-repository-aws-s3:1.2.11:jar" "org.apache.httpcomponents:httpcore:4.4.16:jar" "com.amazonaws:aws-java-sdk-s3:1.12.405:jar" "com.amazonaws:aws-java-sdk-core:1.12.405:jar" "com.fasterxml.jackson.core:jackson-core:2.14.2:jar" "com.fasterxml.jackson.core:jackson-databind:2.14.2:jar" "com.fasterxml.jackson.core:jackson-annotations:2.14.2:jar" "joda-time:joda-time:2.12.2:jar" "org.apache.httpcomponents:httpclient:4.5.14:jar" "commons-io:commons-io:2.12.0"
    #     do
    #        mvn dependency:copy \
    #         --batch-mode \
    #         -DrepoUrl=https://repo.maven.apache.org/maven2 \
    #         -Dartifact=${dep} \
    #         -DoutputDirectory=${HOME}/../lib \
    #         -Dproject.versionNumber=${{ env.PACKAGE_VERSION }} \
    #         -DskipTests=true \
    #         -Dspring.profiles.active=mysql
    #     done
        
    #     ls -la "${HOME}/../lib"
    #   shell: bash

    - name: Build with Maven
      run: 
        mvn clean package -DskipTests=true -Dspring.profiles.active=mysql -Dproject.versionNumber=${{ env.PACKAGE_VERSION }}

    - name: Zip files
      uses: vimtor/action-zip@v1.2
      with:
          files: flyway
          dest: petclinic.mysql.flyway.${{ env.PACKAGE_VERSION }}.zip

    - name: Push a package to Octopus Deploy 🐙
      id: push_a_package_to_octopus_deploy
      uses: OctopusDeploy/push-package-action@v4
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_SERVER_API_KEY }}
        OCTOPUS_SPACE: 'Default'
      with:
        packages: |
          spring-framework-petclinic/target/petclinic2.web.${{ env.PACKAGE_VERSION }}.zip
          petclinic.mysql.flyway.${{ env.PACKAGE_VERSION }}.zip

    - name: Push build information to Octopus Deploy 🐙
      id: push_build_information_to_octopus_deploy
      uses: OctopusDeploy/push-build-information-action@v4
      with:
        octopus_api_key: ${{ secrets.OCTOPUS_SERVER_API_KEY }}
        octopus_server_url: ${{ secrets.OCTOPUS_SERVER_URL }}
        packages: |
          petclinic.mysql.flyway
          petclinic2.web
        version: "${{ env.PACKAGE_VERSION }}" 